// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNvqve5pLz7Qt7H7SZQshCPAYSkX0mAGE',
    appId: '1:950172806830:web:84bd65f12c8e41571c873f',
    messagingSenderId: '950172806830',
    projectId: 'cam-report-22f09',
    authDomain: 'cam-report-22f09.firebaseapp.com',
    storageBucket: 'cam-report-22f09.firebasestorage.app',
    measurementId: 'G-6ST5ZXS98M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWKHb5I9DJ3TlsHC6vSZYt6TesnkLblg',
    appId: '1:950172806830:android:244f1f7adefabdba1c873f',
    messagingSenderId: '950172806830',
    projectId: 'cam-report-22f09',
    storageBucket: 'cam-report-22f09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJs2H-OVq-DCahDx8fnHxz3yQOHDjMCE',
    appId: '1:950172806830:ios:373bbca4847041ea1c873f',
    messagingSenderId: '950172806830',
    projectId: 'cam-report-22f09',
    storageBucket: 'cam-report-22f09.firebasestorage.app',
    iosBundleId: 'com.daff.camreport',
  );
}
